### ISSUE TITLE
Fatal error: Uncaught Error: Class 'OpenAPI\Client\Configuration' not found in xxx

### ISSUE THREAD

**Issue by lilei10101010** [richardpaling/ebay-finances-api#1]
Hello  friend，

  I had download your demos ,

  PHP Version 7.2.10 on windows system  ,

 i created  a new folder "ebayApis" and cd ebayApis ,then  create a composer.json file like this :
{
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/richardpaling/ebay-finances-api.git"
    }
  ],
  "require": {
    "richardpaling/ebay-finances-api": "*@dev"
  }
}

run composer install .
![image](https://user-images.githubusercontent.com/25814376/115646737-52b3e100-a355-11eb-9097-b1b3b607e598.png)

and use your example:
<?php
require_once(__DIR__ . '/vendor/autoload.php');
$token = "AgAAAA";
$config = OpenAPI\Client\Configuration::getDefaultConfiguration()->setAccessToken($token);
?>

it return "Fatal error: Uncaught Error: Class 'OpenAPI\Client\Configuration' not found in xxx"

Dou you know  what  is it , could your help me to slove it ?

**Comment by richardpaling** [comment]
There were some errors in the example.
Please update the package name in your json file 
"macropage/sdk-ebay-rest-finance": "*@dev"
and run 
composer update

Use the full qualified path to call the functions
// Configure OAuth2 access token for authorization: api_auth
$config = \macropage\SDKs\ebay\rest\finance\Configuration::getDefaultConfiguration()->setAccessToken('YOUR_ACCESS_TOKEN');

**Comment by lilei10101010** [comment]
i`m glad to get your  reply  , as you told  me update composer.json to  "macropage/sdk-ebay-rest-finance": "*@dev"  
it work  ! 

However  , it seems there is a new problem  waiting for us .
![image](https://user-images.githubusercontent.com/25814376/115682849-717f9b00-a388-11eb-8e1a-4af83fd05684.png)

 Exception when calling PayoutApi->getPayout: [0] cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apiz.ebay.com/sell/finances/v1/payout

it means  we need to request the api with on  https server ?
Can we develop the code  in a local environment ?
We look forward to your reply ！ I hope you are well today.
