### ISSUE TITLE
how  can i get my access token

### ISSUE THREAD

**Issue by lilei10101010** [richardpaling/ebay-finances-api#2]
Hi There ,  
i have a question ,  how  can i get my  ACCESS TOKEN .
$config = \macropage\SDKs\ebay\rest\finance\Configuration::getDefaultConfiguration()->setAccessToken('YOUR_ACCESS_TOKEN');

i have App ID (Client ID)   ,  Dev ID , Client Secret， How can i get  my access token ?

**Comment by richardpaling** [comment]
developer.ebay.com->signIn->Auth Token For Ebay->OAuth (new security)
